---
- name: Install Docker
  hosts: all
  become: true
  vars:
    docker_dir: "{{ playbook_dir }}/../docker"
    ubuntu_version: jammy
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable"
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ remote_user }}"
        groups: docker
        append: true

    - name: Copy Docker directory
      ansible.builtin.copy:
        src: "{{ docker_dir }}"
        dest: /home/{{ remote_user }}
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: "0755"

    - name: Pull images using Docker Compose
      community.docker.docker_compose_v2_pull:
        project_src: "/home/{{ remote_user }}/docker"
        include_deps: false
